routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::name('changelocale')->get('changelocale', 'TranslationController@changeLocale');

Route::group(['middleware' => 'language'], function () {

	Route::get('/', 'WelcomeController@index')->name('welcome');
	Auth::routes();

	Route::name('front.exams')->get('/front/exams', 'WelcomeController@exams');
	Route::name('front.exam')->get('/front/exams/{id}', 'WelcomeController@exam');
	Route::name('front.search')->post('/front/search', 'WelcomeController@search');
	Route::get('/home', 'HomeController@index')->name('home');

	    //Data Fetch
	Route::name('branches.groups')->get('branches/groups/{branch_id?}', 'BranchController@getPluckedGroups');
	Route::middleware(['auth'])->group(function () {
	    
	    Route::resource('analysis_techniques', 'AnalysisTechniqueController');
	    Route::resource('appointment_types', 'AppointmentTypeController');
	    Route::resource('branches', 'BranchController');
	    Route::resource('groups', 'GroupController');
	    Route::resource('exams', 'ExamController');
	    Route::resource('conditions', 'ConditionController');
	    Route::resource('substances', 'SubstanceController');
	    Route::resource('users', 'UserController');
	    
	});
});

app/Models/AnalysisTechnique.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
 

class AnalysisTechnique extends Model 
{
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'code', 'title_en', 'presentation_en',
         'title_fr', 'presentation_fr',
    ];
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
   

    /**
     * Lesanalyses
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function exams()
    {
        return $this->hasMany(Exam::class);
    }
                 
}

app/Http/Controllers/AnalysisTechniqueController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Models\AnalysisTechnique;
use App\Http\Requests\AnalysisTechniqueRequest;

class AnalysisTechniqueController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $analysis_techniques = AnalysisTechnique::latest()->get();
      
        return view('analysis_techniques.index', compact('analysis_techniques'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $analysis_technique = new AnalysisTechnique();
      
        return view('analysis_techniques.create', compact('analysis_technique'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AnalysisTechniqueRequest $request)
    {
        try
        {  
            $analysis_technique = AnalysisTechnique::create([
                        'code'             => trim($request->input('code')),
                        'title_en'             => $request->input('title_en'),
                        'title_fr'             => $request->input('title_fr'),
                        'presentation_en'             => $request->input('presentation_en'),
                        'presentation_fr'             => $request->input('presentation_fr'),
                    ]);
        }catch (\Exception $e) { 
            Session::flash('status','error');
            $message = trans('message.save_error')." : ". $e->getMessage();
            Session::flash('message',$message );

            return redirect()->back()->with('error', $message);
        }
        $message =__('techniques.created'); 

        Session::flash('success', $message);
        return redirect()->route('analysis_techniques.index')->with('success', $message);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $analysis_technique = AnalysisTechnique::findOrFail($id);
        return view('analysis_techniques.show', compact('analysis_technique'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $analysis_technique = AnalysisTechnique::findOrFail($id);
        return view('analysis_techniques.edit', compact('analysis_technique'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AnalysisTechniqueRequest $request, $id)
    {
        $analysis_technique = AnalysisTechnique::findOrFail($id);

        try
        {  
            $analysis_technique->update($request->all());
        }catch (\Exception $e) { 
            Session::flash('status','error');
            $message = trans('message.save_error')." : ". $e->getMessage();
            Session::flash('message',$message );

            return redirect()->back()->with('error', $message);
        }
        $message =__('techniques.updated'); 

        Session::flash('success', $message);
        return redirect()->route('analysis_techniques.index')->with('success', $message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $analysis_technique = AnalysisTechnique::findOrFail($id);
 
        if(count($analysis_technique->exams)){
    
            $message = __('message.cantdelete');
            Session::flash('error', $message );
            return redirect()->route('analysis_techniques.index')->with('error', $message);

        }
         $analysis_technique->delete();
 
        $message =__('techniques.deleted'); 

        Session::flash('warning', $message);
        return redirect()->route('analysis_techniques.index')->with('warning', $message);
    }
}

resources/views/analysis_techniques/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('analysis_techniques.create')</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('analysis_techniques.store') }}">
                        @csrf

                        @include('analysis_techniques.template', compact('analysis_technique'))
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/analysis_techniques/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('analysis_techniques.edit')</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('analysis_techniques.update', [$analysis_technique->id]) }}">
                        {{ method_field('PUT') }}
                        @csrf

                        @include('analysis_techniques.template', compact('analysis_technique'))
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/analysis_techniques/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">@lang('analysis_techniques.list')</div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    @if (session('success'))
                    <div class="alert alert-success" role="alert">
                        {{ session('success') }}
                    </div>
                    @endif
                    @if (session('error'))
                    <div class="alert alert-danger" role="alert">
                        {{ session('error') }}
                    </div>
                    @endif
                    @if (session('warning'))
                    <div class="alert alert-warning" role="alert">
                        {{ session('warning') }}
                    </div>
                    @endif

                    <div class="box-body table-responsive">
                        <table id="example" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>@lang('analysis_techniques.title_fr') </th>
                                    <th>@lang('analysis_techniques.title_en') </th>
                                    <th>@lang('analysis_techniques.code') </th>
                                    <th>@lang('buttons.details')</th>
                                    <th>@lang('buttons.edit')</th>
                                    <th>@lang('buttons.delete')</th>
                                </tr>
                            </thead>
                            <tbody id="pannel">
                                @include('analysis_techniques.table', compact('analysis_techniques'))
                            </tbody>
                        </table>
                    </div>

                        
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/analysis_techniques/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('analysis_techniques.show')</div>

                <div class="card-body">
                   @lang('analysis_techniques.code') : {{ $analysis_technique->code}} <br/> 
                   @lang('analysis_techniques.title_fr') : {{ $analysis_technique->title_fr}} <br/> 
                   @lang('analysis_techniques.title_en') : {{ $analysis_technique->title_en}} <br/> 
                   @lang('analysis_techniques.presentation_fr') : {{ $analysis_technique->presentation_fr}} <br/> 
                   @lang('analysis_techniques.presentation_en') : {{ $analysis_technique->presentation_en}} <br/> 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/analysis_techniques/table.blade.php
@forelse($analysis_techniques as $analysis_technique)
    <tr id="elem-{{ $analysis_technique->id }}" >
        <td ><a href="{{ route('analysis_techniques.show', [$analysis_technique->id]) }}" >{{ $analysis_technique->title_fr }}</a></td>
        <td > {{ $analysis_technique->title_en}} </td>
        <td>{{$analysis_technique->code}}</td>
        <td><a href="{{ route('analysis_techniques.show', [$analysis_technique->id]) }}" class="btn btn-success" >@lang('buttons.details')</a></td>
        <td>
            <a href="{{ route('analysis_techniques.edit', [$analysis_technique->id]) }}" class="btn btn-warning"> @lang('buttons.edit') </a>
        </td>  
        <td>
            {!! Form::open(['method' => 'delete', 'url' => route('analysis_techniques.destroy', $analysis_technique), 'class' => 'delete', 'data-id' => $analysis_technique->id]) !!}
                <button type="submit" class="btn btn-danger btn-xs pull-right"><i class="fa fa-trash"></i>  @lang('buttons.delete')</button>
            {!! Form::close() !!}
        </td>
    </tr>
@empty
 <tr>
    <p class="text-center margin-half">
        @lang('message.notfoundrecords')
    </p>
</tr>
@endforelse

resources/views/analysis_techniques/template.blade.php
      
@if (session('status'))
<div class="alert alert-success" role="alert">
    {{ session('status') }}
</div>
@endif
      
@if (session('error'))
<div class="alert alert-danger" role="alert">
    {{ session('error') }}
</div>
@endif

<div class="form-group row">
    <label for="code" class="col-md-4 col-form-label text-md-right">@lang('analysis_techniques.code')</label>

    <div class="col-md-6">
        <input id="code" type="text" class="form-control{{ $errors->has('code') ? ' is-invalid' : '' }}" name="code" value="{{ $analysis_technique->code}}" required autofocus>

        @if ($errors->has('code'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('code') }}</strong>
            </span>
        @endif
    </div>
</div> 
<div class="form-group row">
    <label for="title_fr" class="col-md-4 col-form-label text-md-right">@lang('analysis_techniques.title_fr')</label>

    <div class="col-md-6">
        <input id="title_fr" type="text" class="form-control{{ $errors->has('title_fr') ? ' is-invalid' : '' }}" name="title_fr" value="{{ $analysis_technique->title_fr}}" required autofocus>

        @if ($errors->has('title_fr'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('title_fr') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label for="title_en" class="col-md-4 col-form-label text-md-right">@lang('analysis_techniques.title_en')</label>

    <div class="col-md-6">
        <input id="title_en" type="text" class="form-control{{ $errors->has('title_en') ? ' is-invalid' : '' }}" name="title_en" value="{{ $analysis_technique->title_en}}" required autofocus>

        @if ($errors->has('title_en'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('title_en') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label for="presentation_fr" class="col-md-4 col-form-label text-md-right">@lang('analysis_techniques.presentation_fr')</label>

    <div class="col-md-6">
        <textarea id="presentation_fr" rows="3" class="form-control{{ $errors->has('presentation_fr') ? ' is-invalid' : '' }}" name="presentation_fr"  value="{{ $analysis_technique->presentation_fr}}" > </textarea> 

        @if ($errors->has('presentation_fr'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('presentation_fr') }}</strong>
            </span>
        @endif
    </div>
</div>
 
<div class="form-group row">
    <label for="presentation_en" class="col-md-4 col-form-label text-md-right">@lang('analysis_techniques.presentation_en')</label>

    <div class="col-md-6">
        <textarea id="presentation_en" rows="3" class="form-control{{ $errors->has('presentation_en') ? ' is-invalid' : '' }}" name="presentation_en"  value="{{ $analysis_technique->presentation_en}}" > </textarea> 

        @if ($errors->has('presentation_en'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('presentation_en') }}</strong>
            </span>
        @endif
    </div>
</div>
 
<div class="form-group row mb-0">
    <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
            @lang('buttons.submit')
        </button>
    </div>
</div>
             