routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::name('changelocale')->get('changelocale', 'TranslationController@changeLocale');

Route::group(['middleware' => 'language'], function () {

	Route::get('/', 'WelcomeController@index')->name('welcome');
	Auth::routes();

	Route::name('front.exams')->get('/front/exams', 'WelcomeController@exams');
	Route::name('front.exam')->get('/front/exams/{id}', 'WelcomeController@exam');
	Route::name('front.search')->post('/front/search', 'WelcomeController@search');
	Route::get('/home', 'HomeController@index')->name('home');

	    //Data Fetch
	Route::name('branches.groups')->get('branches/groups/{branch_id?}', 'BranchController@getPluckedGroups');
	Route::middleware(['auth'])->group(function () {
	    
	    Route::resource('analysis_techniques', 'AnalysisTechniqueController');
	    Route::resource('appointment_types', 'AppointmentTypeController');
	    Route::resource('branches', 'BranchController');
	    Route::resource('groups', 'GroupController');
	    Route::resource('exams', 'ExamController');
	    Route::resource('conditions', 'ConditionController');
	    Route::resource('substances', 'SubstanceController');
	    Route::resource('users', 'UserController');
	    
	});
});

app/Models/Branch.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
 

class Branch extends Model 
{
     /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
         'title_en', 'presentation_en',
         'title_fr', 'presentation_fr',
    ];
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
                    

    /**
     * Les sous spécialités
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function groups()
    {
        return $this->hasMany(Group::class);
    }
    /**
     * Les analyses
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function exams()
    {
        return $this->hasMany(Exam::class);
    }
    
    // public function exams()
    // {
    //     return $this->hasManyThrough(Exam::class, Group::class);
    // }             
}

app/Http/Controllers/BranchController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Models\Branch;
use App\Models\Group;
use App\Http\Requests\BranchRequest;

class BranchController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $branches = Branch::latest()->get();
      
        return view('branches.index', compact('branches'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $branch = new Branch();
      
        return view('branches.create', compact('branch'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BranchRequest $request)
    {
        try
        {  
            $branch = Branch::create([
                        'title_en'             => $request->input('title_en'),
                        'title_fr'             => $request->input('title_fr'),
                        'presentation_en'             => $request->input('presentation_en'),
                        'presentation_fr'             => $request->input('presentation_fr'),
                    ]);
        }catch (\Exception $e) { 
            Session::flash('status','error');
            $message = trans('message.save_error')." : ". $e->getMessage();
            Session::flash('message',$message );

            return redirect()->back()->with('error', $message);
        }
        $message =__('branches.created'); 

        Session::flash('success', $message);
        return redirect()->route('branches.index')->with('success', $message);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $branch = Branch::findOrFail($id);
        return view('branches.show', compact('branch'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $branch = Branch::findOrFail($id);
        return view('branches.edit', compact('branch'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BranchRequest $request, $id)
    {
        $branch = Branch::findOrFail($id);

        try
        {  
            $branch->update($request->all());
        }catch (\Exception $e) { 
            Session::flash('status','error');
            $message = trans('message.save_error')." : ". $e->getMessage();
            Session::flash('message',$message );

            return redirect()->back()->with('error', $message);
        }
        $message =__('branches.updated'); 

        Session::flash('success', $message);
        return redirect()->route('branches.index')->with('success', $message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $branch = Branch::findOrFail($id);
        // dd(count($branch->exams));
        if(count($branch->groups)|| count($branch->exams)){
            $message = __('message.cantdelete');
            Session::flash('error', $message );
            return redirect()->route('branches.index')->with('error', $message);

        }
         $branch->delete();
 
        $message =__('branches.deleted'); 


        Session::flash('warning', $message);
        return redirect()->route('branches.index')->with('warning', $message);
    }

    /**
     * Rechercher la liste des sous-spécialités d'une spécialité d'une région.
     *
     * @param  Int $branch_id
     * @return \Illuminate\Http\Response
     */
    public function getPluckedGroups(int $branch_id = null)
    {
        if(!isset($branch_id) || is_null($branch_id) )
            return array();

        $branch = Branch::findOrFail($branch_id);
        $groups = Group::where('branch_id', $branch_id)->pluck(trans('message.title'), 'groups.id');
        return $groups;
    }
}

resources/views/branches/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('branches.create')</div>
                <div class="card-body">
                        @include('branches.template', compact('branch'))
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/branches/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('branches.edit')</div>

                <div class="card-body">
                        @include('branches.template', compact('branch'))
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/branches/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">@lang('branches.list')</div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-success" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    @if (session('success'))
                    <div class="alert alert-success" role="alert">
                        {{ session('success') }}
                    </div>
                    @endif
                    @if (session('error'))
                    <div class="alert alert-danger" role="alert">
                        {{ session('error') }}
                    </div>
                    @endif
                    @if (session('warning'))
                    <div class="alert alert-warning" role="alert">
                        {{ session('warning') }}
                    </div>
                    @endif

                    <div class="box-body table-responsive">
                        <table id="example" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>@lang('branches.title_fr') </th>
                                    <th>@lang('branches.title_en') </th>
                                    <th>@lang('buttons.details')</th>
                                    <th>@lang('buttons.edit')</th>
                                    <th>@lang('buttons.delete')</th>
                                </tr>
                            </thead>
                            <tbody id="pannel">
                                @include('branches.table', compact('branches'))
                            </tbody>
                        </table>
                    </div>

                        
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/branches/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('branches.show')</div>

                <div class="card-body">
                   <p>
                    @lang('branches.title_fr') : {{ $branch->title_fr}} <br/>
                     @lang('branches.title_en') : {{ $branch->title_en}} <br/>
                     @lang('branches.groups_count') : 
                     @if(count($branch->groups))
                      <a href="{{ route('groups.index',['branch_id'=>$branch->id])}}"> {{ count($branch->groups)}}</a> 
                       @else 0
                       @endif

                      <br/>
                     @lang('exams.exams_count') : 
                     @if(count($branch->exams))
                      <a href="{{ route('exams.index',['branch_id'=>$branch->id])}}">  {{ count($branch->exams)}} </a>
                       @else 0
                       @endif<br/>
                   </p>
                   @lang('branches.presentation_fr') : <p> {{ $branch->presentation_fr}}</p>
                   @lang('branches.presentation_en') : <p>{{ $branch->presentation_en}}</p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/branches/table.blade.php
@forelse($branches as $branch)
    <tr id="elem-{{ $branch->id }}" >
        <td ><a href="{{ route('branches.show', [$branch->id]) }}" >{{ $branch->title_fr }}</a></td>
        <td > {{ $branch->title_en}} </td>
        <td><a href="{{ route('branches.show', [$branch->id]) }}" class="btn btn-success" >@lang('buttons.details')</a></td>
        <td>
            <a href="{{ route('branches.edit', [$branch->id]) }}" class="btn btn-warning"> @lang('buttons.edit') </a>
        </td>   
        <td>
            {!! Form::open(['method' => 'delete', 'url' => route('branches.destroy', $branch), 'class' => 'delete', 'data-id' => $branch->id]) !!}
                <button type="submit" class="btn btn-danger btn-xs pull-right"><i class="fa fa-trash"></i>  @lang('buttons.delete')</button>
            {!! Form::close() !!}
        </td>
    </tr>
@empty
 <tr>
    <p class="text-center margin-half">
        @lang('message.notfoundrecords')
    </p>
</tr>
@endforelse

resources/views/branches/template.blade.php
      
@if (session('status'))
<div class="alert alert-success" role="alert">
    {{ session('status') }}
</div>
@endif
      
@if (session('error'))
<div class="alert alert-danger" role="alert">
    {{ session('error') }}
</div>
@endif

<?php
    if ($branch->id) {
        $options = ['method' => 'put', 'id'=>'examForm', 'url' => route('branches.update', $branch) ];
    } else {
        $options = [ 'method' => 'post','id'=>'examForm', 'url' => route('branches.store')];
    }
?>
{!! Form::model($branch, $options) !!}
{{ csrf_field() }} 
<div class="form-group row">
    <label for="title_fr" class="col-md-4 col-form-label text-md-right">@lang('branches.title_fr')</label>

    <div class="col-md-6">
        <input id="title_fr" type="text" class="form-control{{ $errors->has('title_fr') ? ' is-invalid' : '' }}" name="title_fr" value="{{ $branch->title_fr}}" required autofocus>

        @if ($errors->has('title_fr'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('title_fr') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label for="title_en" class="col-md-4 col-form-label text-md-right">@lang('branches.title_en')</label>

    <div class="col-md-6">
        <input id="title_en" type="text" class="form-control{{ $errors->has('title_en') ? ' is-invalid' : '' }}" name="title_en" value="{{ $branch->title_en}}" required autofocus>

        @if ($errors->has('title_en'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('title_en') }}</strong>
            </span>
        @endif
    </div>
</div>
<div class="form-group row">
    <label for="presentation_fr" class="col-md-4 col-form-label text-md-right">@lang('branches.presentation_fr')</label>

    <div class="col-md-6">
        <textarea id="presentation_fr" rows="3" class="form-control{{ $errors->has('presentation_fr') ? ' is-invalid' : '' }}" name="presentation_fr"  value="{{ $branch->presentation_fr}}" > </textarea> 

        @if ($errors->has('presentation_fr'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('presentation_fr') }}</strong>
            </span>
        @endif
    </div>
</div>
 
<div class="form-group row">
    <label for="presentation_en" class="col-md-4 col-form-label text-md-right">@lang('branches.presentation_en')</label>

    <div class="col-md-6">
        <textarea id="presentation_en" rows="3" class="form-control{{ $errors->has('presentation_en') ? ' is-invalid' : '' }}" name="presentation_en"  value="{{ $branch->presentation_en}}" > </textarea> 

        @if ($errors->has('presentation_en'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('presentation_en') }}</strong>
            </span>
        @endif
    </div>
</div>
 
<div class="form-group row mb-0">
    <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
            @lang('buttons.submit')
        </button>
    </div>
</div>
 
{!! Form::close()!!}             