routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::name('changelocale')->get('changelocale', 'TranslationController@changeLocale');

Route::group(['middleware' => 'language'], function () {

	Route::get('/', 'WelcomeController@index')->name('welcome');
	Auth::routes();

	Route::name('front.exams')->get('/front/exams', 'WelcomeController@exams');
	Route::name('front.exam')->get('/front/exams/{id}', 'WelcomeController@exam');
	Route::name('front.search')->post('/front/search', 'WelcomeController@search');
	Route::get('/home', 'HomeController@index')->name('home');

	    //Data Fetch
	Route::name('branches.groups')->get('branches/groups/{branch_id?}', 'BranchController@getPluckedGroups');
	Route::middleware(['auth'])->group(function () {
	    
	    Route::resource('analysis_techniques', 'AnalysisTechniqueController');
	    Route::resource('appointment_types', 'AppointmentTypeController');
	    Route::resource('branches', 'BranchController');
	    Route::resource('groups', 'GroupController');
	    Route::resource('exams', 'ExamController');
	    Route::resource('conditions', 'ConditionController');
	    Route::resource('substances', 'SubstanceController');
	    Route::resource('users', 'UserController');
	    
	});
});

app/Models/Condition.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
 
class Condition extends Model  
{ 

	/**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'code',  'title_en',
         'title_fr'
    ];
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];
                  

    /**
     * Lesanalyses
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function exams()
    {
        return $this->hasMany(Exam::class);
    }
                 
}

app/Http/Controllers/ConditionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Models\Condition;
use App\Http\Requests\ConditionRequest;

class ConditionController extends Controller
{
      /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $conditions = Condition::latest()->get();
      
        return view('conditions.index', compact('conditions'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $condition = new Condition();
      
        return view('conditions.create', compact('condition'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ConditionRequest $request)
    {
        try
        {  
            $condition = Condition::create([
                        'code'             => trim($request->input('code')),
                        'title_en'             => $request->input('title_en'),
                        'title_fr'             => $request->input('title_fr'),
                    ]);
        }catch (\Exception $e) { 
            Session::flash('status','error');
            $message = trans('message.save_error')." : ". $e->getMessage();
            Session::flash('message',$message );

            return redirect()->back()->with('error', $message);
        }
        $message =__('conditions.created'); 
 
        Session::flash('success', $message);
        return redirect()->route('conditions.index')->with('success', $message);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $condition = Condition::findOrFail($id);
        return view('conditions.show', compact('condition'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $condition = Condition::findOrFail($id);
        return view('conditions.edit', compact('condition'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ConditionRequest $request, $id)
    {
        $condition = Condition::findOrFail($id);

        try
        {  
            $condition->update($request->all());
        }catch (\Exception $e) { 
            Session::flash('status','error');
            
            $message = trans('message.save_error')." : ". $e->getMessage();
            Session::flash('message',$message );

            return redirect()->back()->with('error', $message);
        }
        $message =__('conditions.updated'); 
 
        Session::flash('success', $message);
        return redirect()->route('conditions.index')->with('success', $message);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $condition = Condition::findOrFail($id);
 
        if(count($condition->exams)){
            $message = __('message.cantdelete');
            Session::flash('error', $message );
            return redirect()->route('conditions.index')->with('error', $message);

        }
         $condition->delete();
 
        $message =__('conditions.deleted'); 
 
        Session::flash('warning', $message);
        return redirect()->route('conditions.index')->with('warning', $message);
    }
}

resources/views/conditions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('conditions.create')</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('conditions.store') }}">
                        @csrf

                        @include('conditions.template', compact('condition'))
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/conditions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('conditions.edit')</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('conditions.update', [$condition->id]) }}">
                    	{{ method_field('PUT') }}
                        @csrf

                        @include('conditions.template', compact('condition'))
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/conditions/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">@lang('conditions.list')</div>

                <div class="card-body">
                    @if (session('status'))
                    <div class="alert alert-info" role="alert">
                        {{ session('status') }}
                    </div>
                    @endif
                    @if (session('success'))
                    <div class="alert alert-success" role="alert">
                        {{ session('success') }}
                    </div>
                    @endif
                    @if (session('error'))
                    <div class="alert alert-danger" role="alert">
                        {{ session('error') }}
                    </div>
                    @endif
                    @if (session('warning'))
                    <div class="alert alert-warning" role="alert">
                        {{ session('warning') }}
                    </div>
                    @endif

                    <div class="box-body table-responsive">
                        <table id="example" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>@lang('conditions.title_fr') </th>
                                    <th>@lang('conditions.title_en') </th>
                                    <th>@lang('conditions.code')</th>
                                    <th>@lang('buttons.details')</th>
                                    <th>@lang('buttons.edit')</th>
                                    <th>@lang('buttons.delete')</th>
                                </tr>
                            </thead>
                            <tbody id="pannel">
                                @include('conditions.table', compact('conditions'))
                            </tbody>
                        </table>
                    </div>

                        
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/conditions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">@lang('conditions.show')</div>

                <div class="card-body">
                   @lang('conditions.title_fr') : {{ $condition->title_fr}} <br/> 
                   @lang('conditions.title_en') : {{ $condition->title_en}} <br/> 
                   @lang('conditions.code') : {{ $condition->code}} <br/> 
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/conditions/table.blade.php
@forelse($conditions as $condition)
    <tr id="elem-{{ $condition->id }}" >
        <td ><a href="{{ route('conditions.show', [$condition->id]) }}" >{{ $condition->title_fr }}</a></td>
        <td > {{ $condition->title_en}} </td>
        <td>{{$condition->code}}</td>
        <td><a href="{{ route('conditions.show', [$condition->id]) }}" class="btn btn-success" >@lang('buttons.details')</a></td>
        <td>
            <a href="{{ route('conditions.edit', [$condition->id]) }}" class="btn btn-warning"> @lang('buttons.edit') </a>
        </td> 
        <td>
            {!! Form::open(['method' => 'delete', 'url' => route('conditions.destroy', $condition), 'class' => 'delete', 'data-id' => $condition->id]) !!}
                <button type="submit" class="btn btn-danger btn-xs pull-right"><i class="fa fa-trash"></i>  @lang('buttons.delete')</button>
            {!! Form::close() !!}
        </td>
    </tr>
@empty
 <tr>
    <p class="text-center margin-half">
        @lang('message.notfoundrecords')
    </p>
</tr>
@endforelse

resources/views/conditions/template.blade.php
      
@if (session('status'))
<div class="alert alert-success" role="alert">
    {{ session('status') }}
</div>
@endif
      
@if (session('error'))
<div class="alert alert-danger" role="alert">
    {{ session('error') }}
</div>
@endif

<div class="form-group row">
    <label for="code" class="col-md-4 col-form-label text-md-right">@lang('conditions.code')</label>

    <div class="col-md-6">
        <input id="code" type="text" class="form-control{{ $errors->has('code') ? ' is-invalid' : '' }}" name="code" value="{{ $condition->code}}" required autofocus>

        @if ($errors->has('code'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('code') }}</strong>
            </span>
        @endif
    </div>
</div> 
<div class="form-group row">
    <label for="title_fr" class="col-md-4 col-form-label text-md-right">@lang('conditions.title_fr')</label>
    <div class="col-md-6">
        <textarea id="title_fr" rows=3 class="form-control{{ $errors->has('title_fr') ? ' is-invalid' : '' }}" name="title_fr" value="{{ $condition->title_fr}}" required autofocus></textarea> 

        @if ($errors->has('title_fr'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('title_fr') }}</strong>
            </span>
        @endif
    </div>
</div> 
<div class="form-group row">
    <label for="title_en" class="col-md-4 col-form-label text-md-right">@lang('conditions.title_en')</label>
    <div class="col-md-6">
        <textarea id="title_en" rows=3 class="form-control{{ $errors->has('title_en') ? ' is-invalid' : '' }}" name="title_en" value="{{ $condition->title_en}}" required autofocus></textarea> 

        @if ($errors->has('title_en'))
            <span class="invalid-feedback" role="alert">
                <strong>{{ $errors->first('title_en') }}</strong>
            </span>
        @endif
    </div>
</div> 
<div class="form-group row mb-0">
    <div class="col-md-6 offset-md-4">
        <button type="submit" class="btn btn-primary">
            @lang('buttons.submit')
        </button>
    </div>
</div>
             